In [16]:
import akshare as ak
import pandas as pd

df = ak.stock_wc_hot_rank(date="20210101")
df.columns= ['index','code', 'name', 'price', 'change', 'hot_value', 
                              'rank','hot_rank', 'base', 'date']
#df = df.iloc[:, 1:10]
df =df[['code', 'name', 'price', 'change', 'hot_value','rank', 'base', 'date']]
df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date')
df

              code   name    price  change  hot_value  rank  base
date
2021-01-01  002612   朗姿股份    45.46   -4.48  1181436.0     1  4054
2021-01-01  000591    太阳能     6.76    5.13  1055592.5     2  4054
2021-01-01  300064  *ST金刚     2.27    3.18  1034369.5     3  4054
2021-01-01  600121   郑州煤电     5.43    0.18   957996.0     4  4054
2021-01-01  600519   贵州茅台  1955.90   -2.11   954499.5     5  4054
...            ...    ...      ...     ...        ...   ...   ...
2021-01-01  688656    浩欧博    71.85   -3.56      591.0  4050  4054
2021-01-01  605228   神通科技     8.99   -0.66      579.0  4051  4054
2021-01-01  300728   天常股份      NaN     NaN      390.0  4052  4054
2021-01-01  300646   侨源气体      NaN     NaN      384.0  4053  4054
2021-01-01  603302   鑫广绿环      NaN     NaN      159.5  4054  4054

[4054 rows x 7 columns]